

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend.py:/app/backend.py
      - ./Data_Final.csv:/app/Data_Final.csv
    command: uvicorn backend:app --host 0.0.0.0 --port 8000 --reload
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
      - TWILIO_SID=AC07196ed31a22b595ac31c1b48a215363
      - TWILIO_FROM_NUMBER=+14059251104
      - TWILIO_TO_NUMBER=+212762045828

  frontend:
    build:
      context: ./Topiary-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Topiary-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
